### PR TITLE
Add :nesting-depth-limit option to LoaderOptions

### PR DESCRIPTION
**Pull request by neeasade**
https://github.com/clj-commons/clj-yaml/issues/81

### CODE REVIEW

**Comment by borkdude** [comment]
@lread LGTM.

**Review by lread — CHANGES_REQUESTED** [review]
Looks really good @neeasade! Thanks for contributing!

I'd like two small changes:
1) can you describe the new `:nesting-depth-limit` option in the `parse-string` docstring? Maybe it would go nicely after `:max-aliases-for-collections`. This includes documenting default value, which is probably inherited from snakeyaml.
2) also mentioning this in the user guide by adding it to:
> Also security related are :allow-recursive-keys and :max-aliases-for-collections options.
would be helpful to users, I think.

**Comment by neeasade** [comment]
Thanks, updated -- any chance I could get a release after this too?

**Comment by lread** [comment]
Awesome, thanks @neeasade!

**Comment by lread** [comment]
And @neeasade, happy to publish a new release if you change your mind, let us know!

**Comment by borkdude** [comment]
@neeasade Note that you can use this project using deps.edn from git as well. You need to run `clojure -X:deps prep` to compile the Java classes in that case.

**Pull request merged**
