### PR TITLE
Bump deps & move Clojure to be a :provided dependency

### PR DESCRIPTION
**Pull request by stig**

### CODE REVIEW

**Comment by slipset** [comment]
I think I’d prefer having Clojure as a :provided dependency. Thoughts?

**Comment by stig** [comment]
> I think I’d prefer having Clojure as a :provided dependency. Thoughts?

TIL! Yeah, :provided scope makes even more sense. Updated PR.

**Comment by stig** [comment]
bump

**Comment by slipset** [comment]
Sorry about the delay, and thanks for work and the reminder!

**Pull request merged**
