### PR TITLE
Upgrade to SnakeYAML 2.1

### LINKED ISSUE #86: Explore Upgrading to SnakeYAML 2.x
SnakeYAML 2.0 has been released:
- [Change log](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes)
- [On Maven](https://central.sonatype.com/artifact/org.yaml/snakeyaml/2.0)

Perceived advantages to upgrade:
- users would not get the current CVE warning for snakeyaml 1.33
- there might be some security fixes included in 2.0 that we did not entirely grok

I'll start with a PR to explore

### PR DESCRIPTION
**Pull request by lread**
See commits for details.

Up for debate: my approach to dealing with unsafe YAML should be questioned.

An interesting alternative would be to also expose the new TagInspectors when using clj-yaml's  `:unsafe` option. But, I think (correct me if I am wrong) we might already have this feature-wise via `:unknown-tag-fn`.

Closes #86

### CODE REVIEW

**Comment by lread** [comment]
New nvd scan CVEs are suppressed for SnakeYAML 1.33, I'll suppress them for SnakeYAML 2.0 as well. Or maybe all versions of SnakeYAML.

**Comment by borkdude** [comment]
@lread If I understand correctly, you passed `unsafe` to the loader and made the change there to make the existing tests pass, right?

**Comment by lread** [comment]
> @lread If I understand correctly, you passed `unsafe` to the loader and made the change there to make the existing tests pass, right?

Thanks for asking @borkdude.
Yes, but only for `:unsafe` mode.
I've modified clj-yaml `:unsafe` behaviour to mimic SnakeYAML 1.33 behaviour.
SnakeYAML 2.0 now has tag inspectors.
The default tag inspector will deny all global tags. 
When using `:unsafe` we mimic SnakeYAML 1.33 and allow all global tags via the `TrustedTagInspector`

**Comment by borkdude** [comment]
That seems a good solution to me. Is there anything you are uncertain about?

**Comment by lread** [comment]
> That seems a good solution to me. Is there anything you are uncertain about?

I've claimed that clj-yaml's `:unknown-tag-fn` is equivalent-ish feature-wise to what SnakeYAML's 2.0 tag inspectors offer. I haven't fully validated that claim.

But... as long as `:unknown-tag-fn` continues to work, that's probably not important at this time.

**Comment by lread** [comment]
I think it might be a good idea to let the dust settle a bit on the SnakeYAML 2.0 release.

Maybe wait a week? Is anybody in a hurry?

For example, [this new commit](https://bitbucket.org/snakeyaml/snakeyaml/commits/39a4b874c70ddf8beb0b73c4092ea1c700cc66df), removes a new SnakeYAML class I used in this PR. Easy to adapt, but there might be other things like this coming in the near term.

**Comment by borkdude** [comment]
Yes, let's wait a month.

**Comment by frenchy64** [comment]
Just to confirm my understanding: this PR is not necessary to resolve any security vulnerabilities because it's already safe to use snakeyaml 1.33 via clj-yaml since clj-yaml is untrusting by default?

**Comment by borkdude** [comment]
@frenchy64 by default, yes

**Comment by lread** [comment]
@frenchy64, yup, that's our understanding and position.

We do plan to upgrade to SnakeYAML 2, but felt it best to wait for the dust to settle.

**Comment by frenchy64** [comment]
Thanks. Is there any way to parse untrusted yaml with clj-yaml 1.0.26? Want to audit my code base for such code.

**Comment by lread** [comment]
> Thanks. Is there any way to parse untrusted yaml with clj-yaml 1.0.26? 

See the user guide: https://github.com/clj-commons/clj-yaml/blob/master/doc/01-user-guide.adoc#unsafe

**Comment by borkdude** [comment]
Yes, via an option:

```
:unsafe true
:unknown-tag-fn ...
```

Check docs for more info.

**Comment by geekingfrog** [comment]
FYI: don't forget to change the project version [there](https://github.com/clj-commons/clj-yaml/pull/87/files#diff-551f87f7577a57c2f4f74b35056d5c7985331f7a38976810fd2bbc213bfe7bb5R10)
I'm currently using this branch in our builds and had to patch it with sed. (not complaining, it's really a filthy workaround for the security scanner at my org)

**Comment by geekingfrog** [comment]
Yes, the clj-yaml version. I missed this workflow, so you're all good.

**Comment by lread** [comment]
@borkdude, it has been about a month... but maybe we'll just [wait until SnakeYAML 2.1 is released](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes)?

In the short term, for this PR, I'll adapt to current 2.1 changes and sync with master.

**Comment by borkdude** [comment]
Yes. I also want to downgrade ordered before a new clj-yaml release since it had some issues with native image.

**Comment by lread** [comment]
> Yes. I also want to downgrade ordered before a new clj-yaml release since it had some issues with native image.

If I get all the privs I need, we'll get a release out of ordered with your for for https://github.com/clj-commons/ordered/issues/71 for native-image sometime soon.

**Comment by lread** [comment]
Seems like we can finally merge this one! Agreed @borkdude?

**Comment by borkdude** [comment]
Yeap!

**Pull request merged**
